developer:
  author: ''
  email: ''
options:
  overrideJava: true
  overrideXml: true
  overrideOther: true
settings:
  javaPath: src/main/java
  resourcesPath: src/main/resources
  fileTypes:
    - type: entity
      suffix: Entity
      packageName: com.example.entity
      ext: .java
      path: src/main/java
      override: true
    - type: mapper
      suffix: Mapper
      packageName: com.example.mapper
      ext: .java
      path: src/main/java
      override: true
    - type: repository
      suffix: Repository
      packageName: com.example.repository
      ext: .java
      path: src/main/java
      override: true
    - type: dao
      suffix: Dao
      packageName: com.example.dao
      ext: .java
      path: src/main/java
      override: true
    - type: service
      suffix: Service
      packageName: com.example.service
      ext: .java
      path: src/main/java
      override: true
    - type: serviceImpl
      suffix: ServiceImpl
      packageName: com.example.service.impl
      ext: .java
      path: src/main/java
      override: true
    - type: controller
      suffix: Controller
      packageName: com.example.controller
      ext: .java
      path: src/main/java
      override: true
    - type: form
      suffix: Form
      packageName: com.example.form
      ext: .java
      path: src/main/java
      override: true
    - type: vo
      suffix: Vo
      packageName: com.example.vo
      ext: .java
      path: src/main/java
      override: true
    - type: query
      suffix: Query
      packageName: com.example.query
      ext: .java
      path: src/main/java
      override: true
    - type: transform
      suffix: Transform
      packageName: com.example.transform
      ext: .java
      path: src/main/java
      override: true
    - type: xml
      suffix: Mapper
      packageName: mapper
      ext: .xml
      path: src/main/resources
      override: true
types:
  - shortName: Object
    longName: java.lang.Object
    isDefault: true
    dbTypes: []
  - shortName: Boolean
    longName: java.lang.Boolean
    dbTypes:
      - ^bit$
      - ^bool # Postgresql
      - ^boolean # Postgresql
  - shortName: Long
    longName: java.lang.Long
    dbTypes:
      - ^bigint
  - shortName: Integer
    longName: java.lang.Integer
    dbTypes:
      - ^tinyint
      - ^smallint
      - ^mediumint
      - ^integer # Postgresql
      - ^interval # Postgresql
      - ^int
  - shortName: String
    longName: java.lang.String
    dbTypes:
      - ^char
      - ^varchar
      - ^text
      - ^longtext
      - ^tinytext
      - ^cidr # Postgresql
      - ^inet # Postgresql
      - ^macaddr # Postgresql
      - ^path # Postgresql
      - ^uuid # Postgresql
      - ^xml # Postgresql
  - shortName: BigDecimal
    longName: java.math.BigDecimal
    dbTypes:
      - ^decimal
      - ^numeric
      - ^money # Postgresql
  - shortName: Float
    longName: java.lang.Float
    dbTypes:
      - ^float
      - ^real # Postgresql
  - shortName: Double
    longName: java.lang.Double
    dbTypes:
      - ^double
  - shortName: LocalDateTime
    longName: java.time.LocalDateTime
    dbTypes:
      - ^datetime
      - ^timestamp
  - shortName: LocalDate
    longName: java.time.LocalDate
    dbTypes:
      - ^date
  - shortName: LocalTime
    longName: java.time.LocalTime
    dbTypes:
      - ^time
